### ISSUE TITLE
RMG-tests Travis build crashes due to psutil dependency issue.

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-tests#18]
```
HEAD is now at 9d3c4df... Deprecate $CONDA_ENV_PATH in .travis.yml
Fetching package metadata .........
Solving package specifications: ..........
Fetching packages ...
libgcc-5.2.0-0 100% |################################| Time: 0:00:00  36.15 MB/s
glib-2.43.0-0. 100% |################################| Time: 0:00:00  48.87 MB/s
pandas-0.18.1- 100% |################################| Time: 0:00:00  50.73 MB/s
harfbuzz-0.9.3 100% |################################| Time: 0:00:00  22.74 MB/s
pango-1.39.0-0 100% |################################| Time: 0:00:00  30.07 MB/s
coolprop-6.0.1 100% |################################| Time: 0:00:00  39.94 MB/s
graphviz-2.38. 100% |################################| Time: 0:00:00  36.49 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
No psutil available.
To proceed, please conda install psutil#
# To activate this environment, use:
# $ source activate rmg_env
#
# To deactivate this environment, use:
# $ source deactivate
#
test version of RMG: /home/travis/build/ReactionMechanismGenerator/code/tested/RMG-Py
could not find environment: tested
```

I believe the following happened:
In the `install.sh` of RMG-tests, we create an anaconda environment `tested` from scratch by fetching the dependencies defined within the RMG-Py repository.

For some unknown reason, the `psutil` dependency could not be fetched, resulting in an incomplete creation of the `tested` environment, thereby crashing the Travis build.

**Comment by connie** [comment]
`psutil` is available from the anaconda channel and works fine on a test local install... not sure what travis is doing.

**Comment by nickvandewiele** [comment]
I agree, I don't think something's wrong with our packages.

Again, I think conda is at blame here, after we started fetching the latest version of miniconda:
https://github.com/conda/conda/issues/2822

The error trace reported there is exactly what is seen in our RMG-tests build.

**Comment by nickvandewiele** [comment]
I am starting to think if it's still a good idea to keep on fetching the latest build of miniconda.

**Comment by connie** [comment]
Hm... perhaps we should not be using the latest then?

**Comment by nickvandewiele** [comment]
When trying to create a new environment from within the RMG-Py repo, it appeared to me that the name of the created environment could not be modified through the `--name` flag. 
E.g.:

```
nickv@rmg:~/ws/Code/tested/RMG-Py$ conda env create --name tested
Error: prefix already exists: /home/nickv/miniconda/envs/rmg_env
nickv@rmg:~/ws/Code/tested/RMG-Py$
```

**Comment by nickvandewiele** [comment]
closed by https://github.com/ReactionMechanismGenerator/RMG-tests/pull/23
