### ISSUE TITLE
WARNING: 'ReactorNet::step(t)' is deprecated. The argument to this function is deprecated and will be removed after Cantera 2.3.

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-tests#22]
These warning pop up in recent Travis builds.

I believe these warnings refer to the calls in [canteraModel ](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/tools/canteraModel.py#L397).

**Comment by JacksonBurns** [comment]
Stale, apparently resolved since we are now on 2.6 https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2288
