### ISSUE TITLE
travis nightly builds?

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-tests#3]
while we are asleep we should use that time to trigger more extensive builds and tests.
- profiling
- more elaborate simulations

**Comment by whgreen** [comment]
Can we have these more extensive builds and tests running on another processor all the time (day and night)?

**Comment by KEHANG** [comment]
@whgreen We are stepping towards this goal with the new functionality of running RMG-tests locally #35. Basically, now we can run the builds and tests on any of our servers with large applications. The only missing piece is to tell the server which newly pushed branches to run RMG-tests. One solution is to create a web page that prepares a queue of branches to be tested and anyone making pull request should go to the web page to add his/her branch to the testing queue.

**Comment by rwest** [comment]
You could use webhooks API to automatically add things to the build/test queue whenever they are pushed. You could have this happen on all pull requests to the official repository, and/or could also give instructions for individuals to configure the webhooks on their own forks.

https://help.github.com/articles/about-webhooks/

**Comment by JacksonBurns** [comment]
The changes described in #86 implement overnight running of builds and automatically execute on pushes to any branch. Closing as completed.
