### ISSUE TITLE
Messages detailing differences refers to wrong model?

### ISSUE THREAD

**Issue by nyee** [ReactionMechanismGenerator/RMG-tests#30]
It looks like the messages from the RMG-tests refers to the wrong model. In build 952, where I fix the R_Addition_COm family, the travis build states the "original model" has new species and reactions associated with the R_Addition_COm family, instead of the test model.

**Comment by KEHANG** [comment]
fixed by [RMG-Py PR](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/875)
