### ISSUE TITLE
RMG tests fails upon one error

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-tests#49]
I think the intended purpose of RMG tests may be similar to unittests, where each one runs independently. Currently, if one example fails in RMG-tests, it is impossible to see the tests after that test which can hide multiple errors. Ideally, in my opinion RMG tests should mention an error message and go to the next example instead of quitting.

**Comment by JacksonBurns** [comment]
The changes described in #86 will attempt to run all tests and upload all results regardless of success or failure. Closing as completed.
