### ISSUE TITLE
RMG-tests creates write-protected files

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-tests#53]
After running RMG-tests, if I try to delete the repository, with the dangerous `rm -r *`, I get an error that some files are write-protected. I can get rid of them with the more dangerous `rm -rf *`. Ideally, the program should be able to be safely cleaned without force removing protected files. 

Maybe having a script for cleaning the directory safely would be helpful in avoiding removal of important files.

**Comment by JacksonBurns** [comment]
Permissions under which RMG is executed have since been fixed and this error no longer occurs. Closing as fixed/stale.
