### ISSUE TITLE
Methane example polymerizes nitrogen

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-tests#55]
The methane example has nitrogen as a reactive species, so it ends up creating species like `N(=NN=[N])N=NN=NN=[N]` and `N([N]N=NN=[N])(N=NN=NN=NN=[N])N=[N]`.

If nitrogen was intentionally set as a reactive species, then we probably need to set a species constraint on the maximum number of nitrogen atoms.

**Comment by KEHANG** [comment]
Okay, thanks! Will add a constraint of `maximumNitrogenAtoms = 2` there.

**Comment by alongd** [comment]
The methane example has only GRI as a seed library (not the GRI-N version), and no other libraries to help RMG with small radical reactions of nitrogen. **So I think it will make sense to make N2 a non reactive species here.** Alternatively, we could use the `GRI-Mech3.0-N` library if we do want N chemistry, and then I would also recommend to restrict maxNatoms to 2 (capture NO, NO2, N2O, N, NH...)

**Comment by KEHANG** [comment]
thanks, @alongd!
