### ISSUE TITLE
Need to migrate to Github Actions

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-tests#77]
It looks like the Travis service was finally shut down.
https://www.travis-ci.org/github/ReactionMechanismGenerator/RMG-tests
We have had no regression tests in three weeks.
It is time to rewrite them on Github Actions.

**Comment by rwest** [comment]
I have attempted to migrate from github-ci.org to github-ci.com. I'm a little confused about what I actually achieved though.

**Comment by rwest** [comment]
> Hello Richard​ ,

> After reviewing your open source qualifications, I am pleased to notify you that 25k credits were added to your account allowing you to resume running OSS builds. When your credits begin running low again, please reach back out to the Support team.

>Credits Consumption Metric
OS.              # CREDITS PER STARTED BUILD MINUTE
Linux.          10
Experimental FreeBSD.         10
Windows.         20
MacOS.         50


>Please let us know if you have any questions! 

>Thanks and happy building!,
​ 
>Your Friends @Travis-CI

>Note: OSS credits may be used solely with respect to open source projects that reside on a public repository. In no event shall OSS credits be used for any commercial project or with respect to any project that resides on a private repository. Travis CI shall determine the amount of all OSS Credit allotments.

So we have 2,500 Linux minutes. Let's see how long that lasts us.

**Comment by rwest** [comment]
So, it seems that Travis spent the last week gradually running the big backlog of test jobs, burned up all our free minutes, and we're stuck again.

https://travis-ci.com/github/ReactionMechanismGenerator/RMG-tests/builds

**Comment by JacksonBurns** [comment]
The changes described in #86 have completed the migration to GH Actions. Closing as completed.
